name: Run Mabl Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run mabl mobile test
      uses: mablhq/mabl-action@v1
      with:
        api-key: ${{ secrets.API_Key }}
        application-id: "Nv0ZecR8RpeHplwOCTsSTQ"
        plan-id: "qulC4XhisnuBV3LvnCbrDg-p"
        environment-id: "wX6fU33nyZCxJUl21wXyXw-a"
        device-type: "real"
        device-name: "Google Pixel 6"
        os-version: "13.0"

